(GH-18) Add author key to all configs
puppetlabs/baker-round pull request #19
Opened 2021-08-23 16:34 UTC by michaeltlombardi

Prior to this commit, the PCT Config files for all templates were
missing the author key. This is necessary to comply with the
namespacing architecture for templates.

This commit adds the author key to every template in this repository
with the value set to puppetlabs.

Resolves #18.

2021-08-23 16:54 UTC, sanfrancrisko requested changes
I think we also need to add the `author` parameter to the [pct-config.yml.tmpl](https://github.com/puppetlabs/baker-round/blob/f023f5ad2d788e8e36236a81710713852010fcd4/puppet-content-template/content/pct-config.yml.tmpl#L1-L7) in the `puppet-content-template` to something like:

```yaml
author: AUTHOR-NAME
```

2021-08-23 17:12 UTC, michaeltlombardi commented
@sanfrancrisko I think that's covered in #17, no?

2021-08-23 22:00 UTC, sanfrancrisko commented
> @sanfrancrisko I think that's covered in #17, no?

It is indeed. By bad

2021-08-24 09:18 UTC, da-ar approved these changes

2021-08-24 09:18 UTC, merged